version: 0.0
os: linux
files:
  - source: /app
    destination: /tmp/app
hooks:
  BeforeInstall:
    - location: app/scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: app/scripts/after_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: app/scripts/start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: app/scripts/stop.sh
      timeout: 300
      runas: root
      